### ISSUE TITLE
Variable scoping

### ISSUE THREAD

**Issue by shaunrampersad** [pcfens/puppet-filebeat#1]
the ERB templates have variables that do not pull from the correct scope. 

filebeat:
  spool_size: <%= @spool_size %>
  idle_timeout: <%= @idle_timeout %>
  registry_file: <%= @registry_file %>
  config_dir: <%= @config_dir %>

This results in a yml file without values. This needs to change to 

filebeat:
  spool_size: <%= scope['::filebeat::spool_size'] %>
  idle_timeout: <%= scope['::filebeat::idle_timeout'] %>
  registry_file: <%= scope['::filebeat::registry_file'] %>
  config_dir: <%= scope['::filebeat::config_dir'] %>

I'm looking into changing this. will submit a PR when done

**Comment by pcfens** [comment]
What version of Puppet are you using?

**Comment by shaunrampersad** [comment]
We are using 4.3.1

**Comment by pcfens** [comment]
I've at least added a test for this, though it took some tweaking of the template because trailing spaces aren't fun to deal with.

**Comment by shaunrampersad** [comment]
great stuff! I've made changes on my local fork, and added tests for it. Still busy with output, shipper, logstash. 

The other issue I've picked up is the formatting of YAML.dump output. It does not indent correctly 
output:
elasticsearch:
  '  hosts':
  - http://1.2.3.4:9200
  '  index': filebeat

Should I create another issue for this?

**Comment by pcfens** [comment]
Could you try re-basing? The updates to get rid of trailing spaces may have changed the output some.

If you're still getting the error, could you also post an example bit of puppet that produces the broken YAML?

**Comment by pcfens** [comment]
Nevermind - it looks like YAML is generated differently in puppet 4 vs. puppet 3.

**Comment by pcfens** [comment]
Can you give the most recent commit a try now? I think that everything is working as expected now.

**Comment by shaunrampersad** [comment]
@pcfens , thanks for the update to the module. It works well now and starts up correctly.

**Comment by shaunrampersad** [comment]
@pcfens, can you update the module on the forge?

**Comment by pcfens** [comment]
I think I already put the latest version up on the forge. Is it not working?
