### ISSUE TITLE
Support additional options in prospector

### ISSUE THREAD

**Issue by amoswood** [pcfens/puppet-filebeat#10]
With the newest version of filebeat (v. 1.1) just out, most people are waiting to use the "multiline" which is not included in the prospector template. There are also quite a few other new options which need to be added.

I list of options from https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html that I see need to be added are:

* [exclude_lines](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_exclude_lines])
* [include_lines](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_include_lines)
* [exclude_files](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_exclude_files)
* [max_bytes](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_max_bytes)
* [multiline](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#multiline)
* [spool_size](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_spool_size)
* [publish_async](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_publish_async)
* [idle_timeout](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_idle_timeout)
* [registry_file](https://www.elastic.co/guide/en/beats/filebeat/1.1/filebeat-configuration-details.html#_registry_file)

Of these, the most important to everyone is the multiline support.

**Comment by amoswood** [comment]
@pcfens , I am working on this now.

**Comment by pcfens** [comment]
I'm working on this as well, and am nearly done

Some of the settings you listed (at least `registry_file`, `idle_timeout`, and `spool_size`) are global settings that can't be applied on a per-prospector level which is why they were left out originally. I'll hopefully be pushing something up shortly.

**Comment by amoswood** [comment]
@pcfens , Do you want me to post what I have? I have added a new test too and am about to test it.

**Comment by pcfens** [comment]
If you already have something then go for it - I don't have any tests around this stuff yet since I've been cleaning up docs.

**Comment by amoswood** [comment]
I have posted https://github.com/pcfens/puppet-filebeat/pull/11 to quick start you to a successful implementation @pcfens .

When do you think that you will merge and create a puppet module?

**Comment by amoswood** [comment]
@pcfens , I have fixed all test and merge issues. I also removed the global settings from the per-prospector level.

**Comment by pcfens** [comment]
This got handled by commit 9730c7fe
