### ISSUE TITLE
Allow newer version than < 2.0 of puppetlabs/powershell

### ISSUE THREAD

**Issue by lahma** [pcfens/puppet-filebeat#105]
It's getting tricky to handle module dependencies when filebeat requires old version. Could you please upgrade to allow < 3.0 ?

Thanks for the great module!

**Comment by pcfens** [comment]
Does the newest version work? Nothing in the changelog suggests it will break, but a second look from someone more familiar with Windows and Powershell is much appreciated.

If it works I'll try and push a new version later today.

**Comment by lahma** [comment]
I manually force-upgraded from 0.3.x (only version that worked with powershell requirement) and it worked for me on Windows Server 2016. I'd say it's pretty safe as users could keep older version if some change would really be needed. Only thing is losing Server 2003 support I guess, but that's just ancient.
