### ISSUE TITLE
generate filebeat configurations programmatically

### ISSUE THREAD

**Issue by calid** [pcfens/puppet-filebeat#107]
Hello,

Would you be open to a PR to generate the filebeat yaml configs programmatically instead of using hardcoded templates?  There are several options currently unsupported, and the current hardcoded template approach doesn't really scale.  For example it's not possible to construct complex `when` conditions for multiple kafka topics with the current approach.

I think it would be better to let the user specify whatever arbitrary config hash they would like in hiera, and just dump that config to the filebeat yaml.  That way there's no more need to stay in sync with all the available options, and permutations of those options.

If this idea is agreeable to you I can work on the code/PR necessary to implement it.

Thanks!

**Comment by pcfens** [comment]
I would prefer that method (and [used it prior to Filebeat 5](https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat1.yml.erb)), but there were issues keeping puppet runs idempotent. Now that we can safely make assumptions about types and Ruby versions it might be reasonable to revisit using a generated config.

**Comment by calid** [comment]
are you referring to the last line in that template, `<%= @filebeat_config.to_yaml() %>`?  Is adding that back essentially all that's needed?

**Comment by pcfens** [comment]
Pretty much. The rest is there to ensure things are typed correctly. The current template can nearly be replaced with that single line if types are entered correctly.

**Comment by calid** [comment]
Sorry maybe a dumb question but when you talk about "making assumptions about types" and "if types are entered correctly," what is "type" referring to?  Puppet resource type?  Filebeat config options?

**Comment by pcfens** [comment]
Data types, particularly strings vs. integers. The YAML parser that filebeat uses (reasonably) asses that quotes mean strings and lack of quotes is detected. If the config file we write out doesn't use and omit quotes correctly then things start to break.

Puppet 4 uses data types that weren't available when the module was written for puppet 3, so that may help. We just need to do some testing to see if it works as expected and if we can or should do any validation before writing user input into a config file.

**Comment by calid** [comment]
mmm gotcha, makes sense

**Comment by pcfens** [comment]
I've done a bit of testing and it looks like newer versions of Filebeat are either more forgiving, or Puppet is being smarter about it (I didn't spend that long digging through it).

Setting the `use_generic_template` to `true` after pulling from the [remove_old_version_support branch](https://github.com/pcfens/puppet-filebeat/tree/remove_old_version_support) will use a [template](https://github.com/pcfens/puppet-filebeat/blob/remove_old_version_support/templates/pure_hash.erb) that just converts the configuration hash to YAML.

If you have a chance to test it out, and everything works, then I'd like to switch that template to the default.

**Comment by pcfens** [comment]
This should be fixed by #118
