### ISSUE TITLE
Issue on Windows - error: Failed to read C:/Program: open C:/Program: The system cannot find the file specified.. Exiting.

### ISSUE THREAD

**Issue by csoleimani** [pcfens/puppet-filebeat#108]
I'm getting this issue when trying to run Puppet on Windows:

Error: Execution of 'c:\Program Files\Filebeat\filebeat.exe -N -configtest -c C:/Program Files/Filebeat/conf.d/sccm_logs
.yml20170523-3620-lmle23' returned 1: Loading config file error: Failed to read C:/Program: open C:/Program: The system
cannot find the file specified.. Exiting.
Error: /Stage[main]/Profile::Sccm/Filebeat::Prospector[sccm_logs]/File[filebeat-sccm_logs]/content: change from {md5}f34
d4cf4c4b0610b984d6eb76ec292bf to {md5}76e01183a3974ae213b624ee870ade1c failed: Execution of 'c:\Program Files\Filebeat\f
ilebeat.exe -N -configtest -c C:/Program Files/Filebeat/conf.d/sccm_logs.yml20170523-3620-lmle23' returned 1: Loading co
nfig file error: Failed to read C:/Program: open C:/Program: The system cannot find the file specified.. Exiting.

It seems like the command should be ran with quotes around it because the space between Program and Files is breaking the command apart. Is this an issue with the module?

**Comment by pcfens** [comment]
Which version of the module are you using? I thought that we had fixed this in version .0.10.1 as part of fixing #75.

**Comment by csoleimani** [comment]
I was using .0.10.0 - I'll try a newer version. Thank you!
