### ISSUE TITLE
Use chocolatey on windows

### ISSUE THREAD

**Issue by edestecd** [pcfens/puppet-filebeat#112]
Not sure how this will effect current users.

DO we need to keep supporting the download with remote_file.
It seems antiquated compared to using a standard package manager like chocolatey.
This has become the standard on windows....

In fact the puppet code will be pretty much the same with a different provider on the package and a few diff paths for config files.

If we stop supporting the old method a major version change is required.

Let me know what you think. I'm glad to contribute the change.

**Comment by pcfens** [comment]
I like the idea of supporting as many install methods as are reasonable. I'm not a Windows person at all, so I don't know how widely chocolatey is used, nor do I have a good way of doing any testing. (I know the windows folks at my current location don't use it, but they also don't use puppet or anything in the same space).

I'm assuming supporting chocolatey is just a `package` resource? Would it be very difficult to add yet another parameter and let users select the install method? If it ends up working well then maybe we look at deprecating the clunky feeling remote_file method.

**Comment by edestecd** [comment]
Yea chocolatey is just a `package` with `provider => 'chocolatey'`.

Yea we could take a parameter for chocolatey with a default of false at first.

**Comment by edestecd** [comment]
I had issues with chocolatey updating to new versions. I could not get it to work so, I will instead fix #109, with the current execs.  Putting the final touches on now.
