### ISSUE TITLE
Latest version is compatible with Puppet >= 3.5!

### ISSUE THREAD

**Issue by snarlistic** [pcfens/puppet-filebeat#116]
Please update compatibility information. Your latest version is compatible with Puppet >= 3.5 and not >= 3.0.0

Using Puppet version 3.4 I receive following error message:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter validate_cmd at filebeat/manifests/config.pp:45 on node...

According to both https://docs.puppet.com/puppet/3/type.html#file and https://docs.puppet.com/puppet/3.5/type.html#file the attribute validate_cmd arrived version 3.5 at the earliest.

**Comment by pcfens** [comment]
All fixed. At some point over the next few months I plan on dropping all support for Puppet 3 since it reached end of life back in December.

**Comment by snarlistic** [comment]
Please accept my apologies. I could and should have sent you a pull request with this commit myself, instead of lazily raising this issue.
