### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B

### ISSUE THREAD

**Issue by tobymaro** [pcfens/puppet-filebeat#120]
Hello,

System:
Windows Server 2008;
Puppet agent: 3.8.3

Code:

`	class { 'filebeat':
	  outputs => {
	    'logstash' => {
	     'hosts' => $log_servers
	    }
	  }
	}`

It works fine on windows server 2012 with PS version 4. But failed on windows 2008 with PS version 3.

Errors:

Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certific
ate verify failed at 27:/etc/puppet/environments/dev/modules/filebeat/manifests/install/windows.pp
Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certific
ate verify failed at 27:/etc/puppet/environments/dev/modules/filebeat/manifests/install/windows.pp
Wrapped exception:
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Error: /Stage[main]/Filebeat::Install::Windows/Archive[C:/Windows/Temp/filebeat-5.1.1-windows-x86_64.zip]/ensure: change
 from absent to present failed: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=SSLv3 read serve
r certificate B: certificate verify failed at 27:/etc/puppet/environments/dev/modules/filebeat/manifests/install/wind
ows.pp

**Comment by pcfens** [comment]
Unfortunately I'm not a windows person at all. Contributors have been very helpful in adding support for Windows to this module. The error almost looks like something related to Puppet itself, but I'm not sure. Hopefully someone else that knows the windows side will be able to jump in here to help.

**Comment by tobymaro** [comment]
Thank You for reply. I applied workaround for this issue. Looks like it related to archive module and windows compatibility. I downloaded the same file via "remote_file" resource successfully and placed it to place where archive module tries to find it.   Works fine.
