### ISSUE TITLE
Invalid parameter beat_name

### ISSUE THREAD

**Issue by dasousa** [pcfens/puppet-filebeat#126]
The config.pp manifest includes the "beat_name" parameter.  The resulting filebeat.yml file generated by $filebeat_config.to_yaml() includes the beat_name attribute.  The Filebeat 5.5 reference manual indicates that the correct parameter for the beat name is 'name' not 'beat_name'.

Also, it would be preferable to not default the name attribute to the FQDN, and letting Filebeat perform the default.  This helps when including Filebeat in an Amazon AMI where you don't want the hostname of the instance used to build the AMI burned into the filebeat.yml file.

**Comment by pcfens** [comment]
Thanks for sending this, and sorry it took so long for a simple fix.

I've moved the 2nd piece of this to a new issue.
