### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by lesinigo** [pcfens/puppet-filebeat#129]
beats are now in the FreeBSD package collection ([under the name "beats"](https://www.freshports.org/sysutils/beats/)), it would be nice to have this module support FreeBSD too

**Comment by lesinigo** [comment]
Pull request #130 solved this issue.

Also, Puppet 4.10 on FreeBSD correctly implements service enabling/disabling so the workaround of pull request #62 shouldn't be needed anymore.

**Comment by pcfens** [comment]
Thanks for catching that #130 solved this one. I'll close it then (if I missed something feel free to re-open)
