### ISSUE TITLE
strings instead of int in the config

### ISSUE THREAD

**Issue by seefood** [pcfens/puppet-filebeat#13]
I set file output, but when it marshals out to the YAML, it's a string (even if I set it without quotes)

      rotate_every_kb: "1024"
      number_of_files: "3"

beats hates it:

 Loading config file error: YAML config parsing failed on /etc/filebeat/filebeat.yml: yaml: unmarshal errors:
   line 12: cannot unmarshal !!str '1024' into int
   line 13: cannot unmarshal !!str '3' into int. Exiting.

**Comment by pcfens** [comment]
Which version of puppet and which version of filebeat are you using? Could you also send a snippet of the error causing puppet code?

I suspect the fix for this is easy, but I want to make sure I'm re-creating it correctly.

**Comment by pcfens** [comment]
After a little mistake, this should be all fixed. It's also updated on the forge as v0.5.5.
