### ISSUE TITLE
Support the `bulk_max_size` output option for logstash

### ISSUE THREAD

**Issue by jarro2783** [pcfens/puppet-filebeat#131]
Can you support the `bulk_max_size` option for the logstash output as documented https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html?

**Comment by pcfens** [comment]
Sorry this took a bit to respond to. It should already be supported. As long as you're using version 2+ of the module, the outputs hash is converted to YAML:

```puppet
class { 'filebeat':
  outputs => {
    'logstash' => {
     'hosts' => [
       'host1',
       'host2',
     ],
     'bulk_max_size' => 4096,
    },
  },
}
```

If that doesn't work let me know so I can try to get it fixed. I'll close this for now, but we can always re-open it something needs tweaking.

**Comment by jarro2783** [comment]
I definitely tried it on the latest version of the module. `filebeat.yml.erb` has a bunch of code that looks like this:
```
output.logstash:
  <%- if @filebeat_config['output']['logstash']['enabled'] != nil -%>
  enabled: <%= @filebeat_config['output']['logstash']['enabled'] %>
  <%- end -%>
  hosts:
  <%- @filebeat_config['output']['logstash']['hosts'].each do |host| -%>
    - <%= host %>
  <%- end -%>
  <%- if @filebeat_config['output']['logstash']['ssl_certificate'] != nil -%>
  ssl.certificate: <%= @filebeat_config['output']['logstash']['ssl_certificate'] %>
  <%- end -%>
```
There is nothing referencing `bulk_max_size`, and I can't see where the whole output hash is written to YAML. Some of the other output types do reference `bulk_max_size`.

**Comment by pcfens** [comment]
Unless you're overriding it, the [default template](https://github.com/pcfens/puppet-filebeat/blob/master/manifests/params.pp#L23) has been replaced with the [`pure_hash.yml.erb`](https://github.com/pcfens/puppet-filebeat/blob/master/templates/pure_hash.yml.erb) template.

Can you try setting `bulk_max_size` to see what happens?

**Comment by jarro2783** [comment]
I just tried it again and it worked as expected. Not sure what I was doing wrong. Thanks for your help.
