### ISSUE TITLE
download_url Regex flagging valid URL's

### ISSUE THREAD

**Issue by jth08527** [pcfens/puppet-filebeat#137]
Starting with version 2.0, valid URL's provided to the download_url parameter get flagged as invalid. This includes the same URL the module would use if no URL is provided. This seems to have been broken with #135 .

To replicate the issue, use module version 2.0 or 2.1, and try to pass the download_url parameter with a valid URL, such as: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.2-windows-x86_64.zip

Use the same URL with version 1.0 or earlier, and everything works fine.

**Comment by pcfens** [comment]
I'm going to guess that #135 fixes this one - I haven't had a chance to push a new release since that was merged. Can you try pulling from master to see if that fixes it?

I'm hoping to push a new release sometime in the next few days.

**Comment by pcfens** [comment]
I just pushed a new version with PR #135 merged. Can you see if version 2.2.0 fixes this?

**Comment by jth08527** [comment]
Sorry for the confusion. I was looking at what I thought was commits that were a part of tag 2.0, but I guess not. I can confirm that 2.2.0 fixes this issue. Thank you.
