### ISSUE TITLE
Default for prospector doc_type should be undef

### ISSUE THREAD

**Issue by sarah-peter** [pcfens/puppet-filebeat#148]
According to the [Beats breaking changes](https://www.elastic.co/guide/en/beats/libbeat/6.0/breaking-changes-6.0.html) for 6.0

> The document_type setting, from the prospector configuration, was removed

However, in `manifests/prospector.pp` it's set by default to "log", so it will always be present in the configuration. I think the default should be "undef" instead, so for 6.0 I can create a prospector configuration without `document_type`.

**Comment by pcfens** [comment]
I'm not sure why this didn't auto-close, so I'm going to close it now.
