### ISSUE TITLE
filebeat 6.1 bin on RHEL path is different

### ISSUE THREAD

**Issue by yurymuski** [pcfens/puppet-filebeat#150]
filebeat 6.1 puts its executable to /usr/bin/filebeat not to /usr/share/filebeat/bin
so puppet fails on filebeat config step. some changes here are needed
https://github.com/pcfens/puppet-filebeat/blob/master/manifests/params.pp#L48

_Error: Execution of '/usr/share/filebeat/bin/filebeat -N -configtest -c /etc/filebeat/conf.d/test.yml20180118-3305-147yed6' returned 1: Error: Could not execute posix command: No such file or directory - /usr/share/filebeat/bin/filebeat
Error: /Stage[main]/Filebeat/Filebeat::Prospector[test]/File[filebeat-test]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/share/filebeat/bin/filebeat -N -configtest -c /etc/filebeat/conf.d/test.yml20180118-3305-147yed6' returned 1: Error: Could not execute posix command: No such file or directory - /usr/share/filebeat/bin/filebeat
Notice: /Stage[main]/Filebeat::Config/File[filebeat.yml]: Dependency File[filebeat-test] has failures: true_

**Comment by yurymuski** [comment]
after creating symlink as workaround
**ln -s /usr/bin/filebeat /usr/share/filebeat/bin/filebeat**
faced with issue that configtest command is expected for 6 vars as 5 has
https://github.com/pcfens/puppet-filebeat/blob/master/manifests/config.pp#L61

**Comment by pcfens** [comment]
I'm going to re-open this since it needs to be fixed even if some folks have a temporary workaround.

**Comment by pcfens** [comment]
Hi @yurymuski - I'm just trying to confirm this one since this is potentially a high priority issue to fix.

On my single RHEL test box runing 6.1.0 I see the binary in both locations so this still works - are you seeing something different? If you are, what version of filebeat are you running, and was it a fresh install from the rpm/repository, or something else?

Thanks!

**Comment by yurymuski** [comment]
Hi @pcfens I miss-configured mirror yum repo  on my machine so instead 6x filebeat i've got 1.x  with the issue missing /usr/share/filebeat/bin/filebeat.
Filebeat 6x has bin file in both locations, so thats not a bug =)
