### ISSUE TITLE
Version 6.x - Load external configuration files

### ISSUE THREAD

**Issue by kobybr** [pcfens/puppet-filebeat#153]
[https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-reloading.html#filebeat-configuration-reloading]

**Comment by pcfens** [comment]
We're doing something like this already to load prospectors - are you suggesting we look at splitting the configuration file out further?

**Comment by kobybr** [comment]
I am in the process of upgrading to 6.x and have been working through the deprecations.   Created this issue as I was going to work on this warning: 

WARN DEPRECATED: config_dir is deprecated. Use `filebeat.config.prospectors` instead. Will be removed in version: 7.0.0
