### ISSUE TITLE
Translate yaml to hash

### ISSUE THREAD

**Issue by somabc** [pcfens/puppet-filebeat#154]
Does anyone know the correct syntax for translating these output options to "hash" for foreman smart parameterized classes?

---
filebeat::outputs:
  logstash:
    hosts:
      - 'localhost:5044'
      - 'anotherserver:5044'
    loadbalance: true

My output settings are not being applied on puppet runs.

**Comment by pcfens** [comment]
Sorry this has taken a while to respond to (I left it alone because I'm not all that familiar with foreman). If you haven't solved this yet can you paste your yaml in a block surrounded by 3 backticks (\```) so we don't lose formatting?

If you have gotten it fixed can we go ahead and close this?

**Comment by somabc** [comment]
Thanks I actually got it working with the above options.
