### ISSUE TITLE
Fact filebeat_version

### ISSUE THREAD

**Issue by M4t3o** [pcfens/puppet-filebeat#159]
Hello

the fact in the master branch (https://github.com/pcfens/puppet-filebeat/blob/master/lib/facter/filebeat_version.rb) use `--version` subcommand instead of `version` (since the 6.x release).

On my side, it returns the deprecated warning on Debian 8.6 for example : 
_Flag --version has been deprecated, version flag has been deprecated, use version subcommand_ 

Regards.

**Comment by pcfens** [comment]
I think this is fixed for *nix systems, but will have to stay broken for windows until we drop support for version 5.x (probably when we add support for 7).

I'll leave this open until then.

**Comment by pcfens** [comment]
After pushing a few fixes this afternoon I'm going to go ahead and close this. If you're already running version 6 then the messages should go away. It'll only use the deprecated method to determine version if the major version can't be determined based on the path.
