### ISSUE TITLE
Issue downloading from puppet forge

### ISSUE THREAD

**Issue by chad-upton** [pcfens/puppet-filebeat#16]
Puppetserver 2.2.1
Amazon Linux 

```
puppet module install pcfens-filebeat
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'pcfens-filebeat' (???)
  No version of 'pcfens-filebeat' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

```
puppet module install pcfens-filebeat --ignore-dependencies
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└── pcfens-filebeat (v0.5.7)
```

**Comment by pcfens** [comment]
What version of puppet are you running when you run `puppet --version`. Also, could you try installing in an alternate modulepath like `puppet module install pcfens-filebeat --modulepath=temp`?

If that works, do you mind sharing the output of `puppet module list`?

**Comment by pcfens** [comment]
Hi @chad-upton -

Have you had a chance to try installing to a different path? I'm hoping you'll find some dependency mis-match with some other module.

**Comment by pcfens** [comment]
I'm going to go ahead and close this - if the problem wasn't resolved we can re-open it.

**Comment by ankh2054** [comment]
thanks for your module,= by the way. I'm having the same issue. Below is list of my modules.

`├── ayohrling-local_security_policy (v0.6.0)
├── puppetlabs-apache (v1.10.0)
├── puppetlabs-apt (v2.3.0)
├── puppetlabs-concat (v2.2.0)
├── puppetlabs-powershell (v2.1.0)
├── puppetlabs-stdlib (v4.15.0)
└── spotify-puppetexplorer (v1.1.1)`

Puppet version - 4.8.1

**Comment by ankh2054** [comment]
`Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=pcfens-filebeat
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=pcfens-filebeat&limit=20&offset=20
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&limit=20&offset=20
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&limit=20&offset=40
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-apt
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-apt&limit=20&offset=20
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-powershell
Debug: Failed to load library 'pe_license' for feature 'pe_license'
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=lwf-remote_file
Debug: Failed to load library 'pe_license' for feature 'pe_license'`

**Comment by pcfens** [comment]
Are you using PE or open source then? None of the requirements for filebeat require PE, so a lack of license shouldn't have an impact here.

**Comment by ankh2054** [comment]
I just installed by ignoring dependencies and all works fine :)

**Comment by ankh2054** [comment]
Using open source
