### ISSUE TITLE
Error with queue_size been removed

### ISSUE THREAD

**Issue by malagace2** [pcfens/puppet-filebeat#160]
Hello,

When I run "puppet agent -t" I receive this error message:

`Error: /Stage[main]/Filebeat::Config/File[filebeat.yml]/content: change from {md5}372f9bd50cb5445dbd20be7e25f164bb to {md5}5df1557e2cdad6e28b85430b9cbc19e8 failed: Execution of '/usr/share/filebeat/bin/filebeat -N -configtest -c /etc/filebeat/filebeat.yml20180405-18063-1n2d3ob' returned 1: Flag --configtest has been deprecated, configtest flag has been deprecated, use test config subcommand Exiting: 1 error: setting 'queue_size' has been removed`

`    class { 'filebeat':
        outputs => {
         'elasticsearch' => {
                'hosts'         => [
                    'Something-int:9200',
                    'Something:9200'
                ],
                'protocol'      => 'https',
                'username'      => 'something',
                'password'      => 'Something',
                'registry_file' => '/var/lib/filebeat/registry',
                'major_version' => '6',
                'package_ensure' => 'latest',
                'ssl.certificate_authorities' => '/Path ssl/',
          },
       },
     }
    filebeat::prospector { 'syslogs':
        paths         => [
            '/var/log/*.log',
            '/var/log/*/*',
            '/var/log/*',
        ],
        doc_type      => 'syslog-beat',
        exclude_files => ['\.dat$', '\.gz$', 'filebeat'],
    }
    filebeat::prospector { 'client-prod':
        paths         => [
            '/folder/client/*.log',
        ],
        doc_type      => 'syslog-beat',
        exclude_files => ['\.dat$', '\.gz$', 'filebeat'],
    }
`
I try removing the filebeat package on Centos and let puppet reinstalling but I have the same issue
Let me know if you need more information

**Comment by pcfens** [comment]
I'm a little stumped since it looks like you're explicitly setting `major_version` to something other than 5.

The error suggests that puppet is trying to run the validate command that should only be running when version 5 is installed. Another set of eyes on [the code](https://github.com/pcfens/puppet-filebeat/blob/master/manifests/config.pp#L58-L63) would be appreciated - maybe you'll see the error more quickly than I do.

**Comment by malagace2** [comment]
According to the readme:
To upgrade to Filebeat 6.x, simply set $filebeat::major_version to 6 and $filebeat::package_ensure to latest.

According to the code, the default version is now version 6 ?

**Comment by malagace2** [comment]
I will close the ticket my settings were under filebeat::output class instead of filebeat class

Sorry
