### ISSUE TITLE
Unknown variable: '::filebeat_version'

### ISSUE THREAD

**Issue by miranovy** [pcfens/puppet-filebeat#167]
When i start puppet first time (filebeat package not installed) will appear warning:

> Warning: Unknown variable: '::filebeat_version'. at /etc/puppet/service/modules/filebeat/manifests/config.pp:57:6
Warning: Unknown variable: '::filebeat_version'. at /etc/puppet/service/modules/filebeat/manifests/prospector.pp:50:6

If filebeat package is already installed the warning does not appear.

```
class service_filebeat()
{

  package { 'apt-transport-https':
        ensure => 'latest',
  } ->
 
  class { 'filebeat':
    major_version => '5',
  }

  filebeat::prospector { 'my_prospector':
    paths      => [ '/var/log/foo/*.log' ],
    input_type => 'log',
    doc_type   => 'log',
  }

}

```

**Comment by snahelou** [comment]
Same for me on RHEL like. 

filebeat need to be installed before running this class :'(

**Comment by anton-kyrylenko** [comment]
Module version 3.2.1
Debian 8 

If you have error like

`Error: Facter: error while resolving custom fact "filebeat_version": undefined method []' for nil:NilClass
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: '::filebeat_version'. at /etc/puppetlabs/code/environments/production/modules/filebeat/manifests/config.pp:72:6 on node`

and old filebeat version is installed , try to removing filebeat manualy  
(1.x.x  in my case).
Works for me.
