### ISSUE TITLE
Windows filebeat install doesn't execute Exec["install ${filename}"]

### ISSUE THREAD

**Issue by dannygoulder** [pcfens/puppet-filebeat#170]
When using the module to install version 6.2.4 on Windows, it appears that the `install ${filename}` exec doesn't get run.  As a result the service isn't installed.

I'll work on doing some further debugging - but it seems like the `refresh` event doesn't seem to trigger the `exec`.

Perhaps it can be changed to only run if the service isn't installed, with an `onlyif` for example.  It shouldn't cost too much resource to do a `get-service filebeat`

I'll see if I can get it working and submit a PR if that will help.

**Comment by pcfens** [comment]
Thanks for finding the problem. I'm not a Windows user/admin/dev at all and someone else added Windows support in a PR. I'd very much appreciate any help on this or any other Windows things.

**Comment by dannygoulder** [comment]
I've got something working (but it requires chocolatey to install the package).  Chocolatey installs the package in a non-standard location (which is apparently [standard for chocolatey](https://chocolatey.org/packages/filebeat#comment-3619601744)), but it appears to work.

Is switching to chocolatey an acceptable approach for Windows installation (please say yes!!)?

**Comment by pcfens** [comment]
I don't see any issue with using Chocolatey. Is Chocolatey widely used enough to where it would make sense to completely replace the file download method, or should we leave it in there and just note that it might not work as smoothly as the package install?

**Comment by dannygoulder** [comment]
The filebeat chocolatey package has had nearly 10,000 downloads of the latest version since April, which i think makes it reasonably popular.

However I do think that the non-standard install location might prove to be a sticking point, and removing the manual download method entirely is probably a bit extreme! Let me try to add a parameter to control the installation method - it will be quite complex due to the change in installation path.

**Comment by dannygoulder** [comment]
I've opened #171 which replaces the old method with chocolatey (and updates facts and tests).

As I mentioned above, I can work on adding a $install_provider param (or similar) to allow to select how the installation is done

**Comment by skyrawrcode** [comment]
I'm not sure if it is related but i thought i was experiencing this issue where it was not running. After some debugging i found that the version of puppetlabs/powershell I was using (2.0.2) at the time had a bug that did not respect cwd. I have upgraded to 2.2.0 and it appears to be working as of now.

**Comment by dannygoulder** [comment]
Thanks! That sounds really promising, and might explain why others have indicated (in the PR) that there wasn’t a problem. I’ll do some more testing and we can hopefully close this with an update to the dependency metadata

**Comment by skyrawrcode** [comment]
Here is the ticket that pointed me in this direction. https://tickets.puppetlabs.com/browse/MODULES-3565

**Comment by dannygoulder** [comment]
Thanks! I checked this out and it was indeed a bug with the powershell module.  I've bumped the powershell module and everything works again
