### ISSUE TITLE
Support for autodiscover

### ISSUE THREAD

**Issue by Wimmesberger** [pcfens/puppet-filebeat#178]
Hi there!

Filebeat 6.1.0 or higher added an interesting feature to autodiscover docker applications and dynamically configure filebeat to collect logs from them.
[Filebeat: Autodiscover](https://www.elastic.co/guide/en/beats/filebeat/6.3/configuration-autodiscover.html)

However it is currently not possible to configure it using this puppet module.

I have attached an example config that works in our environment: [filebeat.yml.txt](https://github.com/pcfens/puppet-filebeat/files/2201215/filebeat.yml.txt)
The containers are started by rancher and we have added a custom label 'elk' on containers, who's logs should be shipped.

I would suggest to add one more variable which is merged into the config hash, similar to how the modules-array is added

Thank you for your time :)

**Comment by marcinbojko** [comment]
Hi, I'd also leave a request for autodiscover, it looks very promising.

**Comment by jamesooo** [comment]
I wrote some code for this - hopefully it can be merged in soon

**Comment by pcfens** [comment]
Just merged #278.
