### ISSUE TITLE
Service not running automaticlly 

### ISSUE THREAD

**Issue by roiromanoclick** [pcfens/puppet-filebeat#181]
After the installation on my client centos 7 ( with ppupet) , the service filebeat is in stop state. 
please assit, maybe i should confiure somethong on thr module? where ?

**Comment by roiromanoclick** [comment]
i think the service not running becouse the filebeat.yml not configure output. this is the error i get: 
Error: Execution of '/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml20180808-12499-147hw35 test config' returned 1: Exiting: error initializing publisher: No outputs are defined. Please define one under the output section.
Error: /Stage[main]/Filebeat::Config/File[filebeat.yml]/content: change from '{md5}8e2a63c4664e8ad658dadef286beb82d' to '{md5}5b216f0bb562aa68411019fca39e972c' failed: Execution of '/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml20180808-12499-147hw35 test config' returned 1: Exiting: error initializing publisher: No outputs are defined. Please define one under the output section.
 sone one can guide me where to configure it on the main module?

**Comment by pcfens** [comment]
The [usage section](https://github.com/pcfens/puppet-filebeat#usage) of the documentation explains how to set up some of the required fields like outputs and prospectors.

Understanding how filebeat needs to be configured will help too. The module is just a tool to manage the [filebeat configuration](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-howto-filebeat.html).
