### ISSUE TITLE
filebeat::fields_under_root: true is not respected in filebeat::prospectors

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [pcfens/puppet-filebeat#206]
Hi,
I've found that `filebeat::prospectors` doesn't care about `filebeat::fields_under_root: true` or false.
It looks that it has hardcoded value of `false`.
I've provided a patch that changes this approach to follow `filebeat::fields_under_root`

https://github.com/pcfens/puppet-filebeat/pull/205

**Comment by pcfens** [comment]
Fixed by merging #205
