### ISSUE TITLE
http metrics endpoint configurable

### ISSUE THREAD

**Issue by nielsole** [pcfens/puppet-filebeat#209]
Filebeat supports a metric endpoint that can be used to monitor filebeat:
https://www.elastic.co/guide/en/beats/filebeat/master/http-endpoint.html
```
The HTTP endpoint has the following configuration settings:

http.enabled
    (Optional) Enable the HTTP endpoint. Default is false. 
http.host
    (Optional) Bind to this hostname or IP address. It is recommended to use only localhost. Default is localhost 
http.port
    (Optional) Port on which the HTTP endpoint will bind. Default is 5066. 
```

Currently enabling this endpoint is not exposed by this module.

It would be really cool if these configuration options were to be added.
What is your opinion about this?

**Comment by pcfens** [comment]
I just published v4.0 of the module that should include this. Sorry for the long delay in getting to it.
