### ISSUE TITLE
Yum repo update to work with version 7

### ISSUE THREAD

**Issue by trenta** [pcfens/puppet-filebeat#217]
Manually using the following:
```
[elastic-7.x]
name=Elastic repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md

```

The module spits out the following that for some reason only show 6.x version of filebeat:
```
[beats]
name=elastic beats repo
baseurl=https://artifacts.elastic.co/packages/7.x/yum
enabled=1
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
```

**Comment by pcfens** [comment]
Did the machine you're running this on previously have filebeat 6.x installed? I'm wondering if we need to clean out the yum cache when we modify the repository to keep it from searching the cached package list.

I've got a change staged up if that ends up being the case.

**Comment by trenta** [comment]
Yes it did.  That may be all it takes.  I couldn't see why the yum repo file from the module wouldn't work.

**Comment by pcfens** [comment]
Can you check if the code in master fixes this problem? I've pushed the change, but don't have a good place to test it (I run master in production, but we're not quite ready for 7.x yet).

**Comment by trenta** [comment]
Yep that fixed it.  Cheers.

**Comment by pcfens** [comment]
Thanks for the help. I just put the change in a new release (4.0.2).
