### ISSUE TITLE
Typo in logstash/elasticsearch TLS configuration

### ISSUE THREAD

**Issue by stith** [pcfens/puppet-filebeat#23]
Howdy y'all!

Found a quick typo in the `filebeat.yaml` templates for logstash and elasticsearch's TLS configuration:

https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat.yml.ruby18.erb#L81-L83
https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat.yml.ruby18.erb#L137-L139

Looks like you're checking for `certifcate_key` (typo, missing i in certificate) and then using `certificate_key` (spelled correctly) in the actual output. :smile:

**Comment by pcfens** [comment]
Thanks for finding this - I've patched and pushed a new release up to the forge as v0.6.1

**Comment by stith** [comment]
Thanks for the quick fix! You missed the logstash one though, which is the one that I'm actually trying to use hehehe.

https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat.yml.ruby18.erb#L137-L139

**Comment by pcfens** [comment]
Oops :) - moving a little too fast. 

I've pushed this fix up as v0.6.2.

Thanks again.
