### ISSUE TITLE
Wrong fix for Issue - 228 ? Processors should be Array and not Hash.

### ISSUE THREAD

**Issue by anandinhere** [pcfens/puppet-filebeat#231]
This is from changelog under [v3.0.0 ](https://github.com/pcfens/puppet-filebeat/blob/master/CHANGELOG.md#v300)

[Issue-228](https://github.com/pcfens/puppet-filebeat/issues/228)

> Processors should be an array of hashes #157, #156
> #157
> #156

This seems to be done right. Why is it reverted now? I don't think it's the code that needed a fix here. Rather the documentation is what should be fixed.

**Comment by pcfens** [comment]
Can you confirm that this is fixed in master, preferably with a short code snippet as an example so I can update the documentation too (or a PR)?

Thanks!
