### ISSUE TITLE
Add support for chocolatey

### ISSUE THREAD

**Issue by hdep** [pcfens/puppet-filebeat#234]
Hi,

I think it would be great if we can install filebeat from chocolatey.
Are you open to PR on this subject ? 

The first step to do this is to create a variable like use_chocolatey which should be default to no as this will not affect current behaviour.

What do you think ?

**Comment by pcfens** [comment]
Sorry for the delay.

I'd love to support chocolatey, but I don't know enough about it or have access to a place to test to write it myself. All of the Windows support here is from PRs, so feel free to send something along if you have the time.

Thanks!
