### ISSUE TITLE
Problems installing filebeat on Windows

### ISSUE THREAD

**Issue by bertaviader** [pcfens/puppet-filebeat#242]
Hey,

I'm trying to install the module on Windows, we use foreman for all the classes on the puppet. I've downloaded the github code to our system. But when I try to run puppet agent -t this error appears: Error: Failed to apply catalog: Parameter provider failed on Exec [unzip filebeat-6.2.4-windows-x86_64]: Invalid exec provider 'powershell' (file: /modules/filebeat/manifest/install/windows. pp, line: 40)

I've  also installed the module powershell https://forge.puppet.com/puppetlabs/powershell.

I don't know what I should do next, can you help me?

Thanks,
Berta

**Comment by pcfens** [comment]
Everything should work once you have the powershell module installed, so I'm not really sure what might be happening.

Can you confirm that the provider is sync-ing to the client as expected?

**Comment by bertaviader** [comment]
When I run the puppet agent -t this shows:

![image](https://user-images.githubusercontent.com/18306366/74141061-898d5380-4bf6-11ea-82bd-a21bd96c0030.png)

Also if I try to install the powershell module again it displays that is already installed.

![image](https://user-images.githubusercontent.com/18306366/74141277-e852cd00-4bf6-11ea-9e9f-a006227a9e13.png)

Do you need more information?
The OS is Windows Server 2016 64-bits
The puppet agent is version 5.x

Thank you!
Berta

**Comment by pcfens** [comment]
It looks like you're installing the powershell module in your`production` environment but running the agent in your `devbertafacter` environment.

**Comment by bertaviader** [comment]
Thanks!! It was for environment. 
I will close the issue then!
