### ISSUE TITLE
Unable to set encoding & other options with docker/syslog input types

### ISSUE THREAD

**Issue by GiedriusS** [pcfens/puppet-filebeat#248]
With the change here https://github.com/pcfens/puppet-filebeat/blob/8ff54883c4ee0b9a9d2742a2d67759bb3d3f70c8/templates/input.yml.erb (https://github.com/pcfens/puppet-filebeat/commit/8ff54883c4ee0b9a9d2742a2d67759bb3d3f70c8) we have this now:

```
  <%- if @input_type == 'docker' -%>
  containers:
    ids:
    <%- @containers_ids.each do |id| -%>
    - <%= id %>
    <%- end -%>
    path: <%= @containers_path %>
    stream: <%= @containers_stream %>
  combine_partial: <%= @combine_partial %>
  cri.parse_flags: <%= @cri_parse_flags %>
  <%- elsif @input_type == 'syslog' -%>
  protocol.<%= @syslog_protocol %>:
    host: <%= @syslog_host %>
  <%- else -%>
  paths:
  <%- @paths.each do |log_path| -%>
  - <%= log_path %>
  <%- end -%>
  <%- if @encoding -%>
  encoding: <%= @encoding %>
  <%- end -%>
...
```

Before (https://github.com/pcfens/puppet-filebeat/blob/46a2c515d101e66f55aa3d1d6f02d16725fbaef6/templates/prospector.yml.erb):

```
- type: <%= @input_type %>
  <%- if @input_type != 'docker' -%>
  paths:
  <%- @paths.each do |log_path| -%>
  - <%= log_path %>
  <%- end -%>
  <%- else -%>
  containers:
    ids:
    <%- @containers_ids.each do |id| -%>
    - <%= id %>
    <%- end -%>
    path: <%= @containers_path %>
    stream: <%= @containers_stream %>
  combine_partial: <%= @combine_partial %>
  cri.parse_flags: <%= @cri_parse_flags %>
  <%- end %>
  <%- if @encoding -%>
  encoding: <%= @encoding %>
  <%- end -%>
...
```

The field `encoding` was outside of the `if` clause so it was possible to set the option `encoding` and other important options such as `fields` even when using the `docker` or `syslog` input types.

AFAICT an error occurred during this refactoring - that `if` clause needs to end before the handling of the `encoding` option. Hence, it is impossible to use those options with the `docker` and `syslog` input types.

Thoughts? :)

**Comment by pcfens** [comment]
Do you have a test snippet of code that re-creates the error? If I'm counting my if/else/end blocks correctly the encoding piece should still work. Are there other options that work without Docker and Syslog that we're missing?

**Comment by pcfens** [comment]
Thanks! I'll close this since it was closed in #249.

**Comment by GiedriusS** [comment]
Sorry for the late response. https://github.com/pcfens/puppet-filebeat/pull/249 indeed fixes some things and thank you for the PR but I believe that there are other options that are still impossible to set. For example, the `json` key (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-docker.html#filebeat-input-docker-config-json) or `scan_frequency` (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-docker.html#filebeat-input-docker-scan-frequency). Maybe we should revisit this? I can do a PR on this if it would be accepted :P

**Comment by GiedriusS** [comment]
@pcfens @jbehrends kind ping ^
