### ISSUE TITLE
xpack parameter for filebeat 7.x creates issue with pcfens/puppet-filebeat 4.3.1

### ISSUE THREAD

**Issue by abrahmankar** [pcfens/puppet-filebeat#252]
I've ELK 7.4.2 version. I am trying to have elasticsearch as filebeat output as well as monitoring enabled on monitoring node. 

when I use **filebeat.xpack.monitoring** I get following Error. **"Exiting: 'xpack.monitoring.elasticsearch.hosts' and 'output.elasticsearch.hosts' are configured"**.

As per elasticsearch docs for 7.4 version, xpack is deprecated and when I use **filebeat.monitoring** it works as expected.

**Comment by pcfens** [comment]
When support is dropped for Filebeat 6.x (or whichever version of 7.x it's removed in) we'll likely want to drop that parameter, but removing it before then may break things for folks still using it.

**Comment by abrahmankar** [comment]
that's true. Till then any future plans to release version of pcfens for ELK 7.x version which will handle not only this change but other config related changes as well.

**Comment by pcfens** [comment]
Is there anything specific that you're looking for? This module is essentially converting a puppet hash to YAML, so nearly every option should be supported.

There are very few options in the base configuration that are explicitly enabled/disabled on the puppet side of things. The inputs are a little different, but there's a hash configuration option that should expose everything.

**Comment by abrahmankar** [comment]
As of now I just want monitoring parameter like we have xpack. This will suffice my use case.

**Comment by pcfens** [comment]
I added the monitoring parameter so that you can set that directly now. If that works I'll try and get a new release out early next week.

**Comment by abrahmankar** [comment]
Thanks a lot. Will try in couple of days.
