### ISSUE TITLE
Creation of service.yml in /etc/filebeat/modules.d directory

### ISSUE THREAD

**Issue by sdrose** [pcfens/puppet-filebeat#263]
Hello.
Does this module allow for both the creation / modification of a service .YML file in /etc/modules.d directory from a puppet run?  What is the syntax for this?

Does the filebeat module allow for enabling and disabling a particular service from a puppet run?  If so, what is the syntax?

**Comment by pcfens** [comment]
This module manages inputs and the main filebeat configuration file, but only using puppet manifests or hiera (we don't support tasks). I'm assuming when you say service you're referring to what filebeat calls an [input](https://www.elastic.co/guide/en/beats/filebeat/master/how-filebeat-works.html#input).

To create an input, you'd add some syntax [like this](https://github.com/pcfens/puppet-filebeat#adding-an-input) to your manifests. To remove the input you'd delete it or comment it out in your puppet manifest. In each case Puppet does it's thing and makes sure that the configuration on the managed host matches what your manifests say it should be.

I hope that answers your question - feel free to comment if you'd like more clarification.
