### ISSUE TITLE
Installing Filebeat modules

### ISSUE THREAD

**Issue by tomashejatko** [pcfens/puppet-filebeat#280]
Hi, 

first I want to apologize that I don't know if this right place to write my question, but I don't know about any other channel to contact authors :)

My question is: can this Puppet module (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#enable-modules) ? IIRC it can only create configuration for them, but I must enable them manually? Do somebody have workaround here? I want to install multiple nodes with modules and will be missing piece in automatization.

If I am correct and module can't enable them, should you please write it down in limitations?
If I am not correct and just missing something, I am sorry to bother you ;)

Thanks for answers!

**Comment by pcfens** [comment]
There are a few different [module parameters](https://github.com/pcfens/puppet-filebeat#class-filebeat) in the main class. Do any of those do what you need?  I don't have any personal experience using filebeat modules, but I thought we had them all working as expected (thanks to all the contributors that worked on it)

**Comment by tomashejatko** [comment]
Hello, I had bit panicked on this. Later I've figured out how to do this. Thanks for amazing work and sorry for rushing into creating this issue!

**Comment by styleart** [comment]
Hey @tomashejatko , sorry to bother you, but could you help with a hint how to enable modules? The config is working fine, but I have the same issue that modules are just not enabled (`filebeat modules list` show nothing for enabled) and I already spent hours on trying out everything.
