### ISSUE TITLE
Unable to set registry path

### ISSUE THREAD

**Issue by ryan-dyer-sp** [pcfens/puppet-filebeat#284]
Support for registry_file was removed in logstash 7, however it was replaced with registry path.  Currently I cannot find any way to modify the registry path.
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#_registry_path

**Comment by ryan-dyer-sp** [comment]
@pcfens can you provide an ETA on when a release containing the changes will be done?

**Comment by pcfens** [comment]
I just pushed 4.11.0 a few minutes ago. This is the only change in the release, so hopefully upgrading is easy.

Thanks a ton for sending a PR with the issue.
