### ISSUE TITLE
bump puppet-archive dependency

### ISSUE THREAD

**Issue by skoef** [pcfens/puppet-filebeat#288]
I'm having trouble upgrading some of my modules because `pcfens-filebeat` is constraining (perhaps too strict?) to `puppet-archive` < 5.0.0. Could you investigate the compatibility of this module with `puppet-archive` < 6.0.0 for instance?

Perhaps this goes for `puppetlabs-stdlib` as well, which has released 7.x.

**Comment by shamil** [comment]
@pcfens we are also hit by this problem. If this is an acceptable change to do I can create a PR for this, let me know...
