### ISSUE TITLE
Missing "port" option for logstash config

### ISSUE THREAD

**Issue by stith** [pcfens/puppet-filebeat#29]
As mentioned in the [filebeat docs](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#port), there's a `port` option so you don't have to specify the port for each host in `hosts`. This is useful if you want to, for example, query your list of logstash hosts from PuppetDB, which will result in raw hostnames without ports suffixed.

**Comment by pcfens** [comment]
Thanks for finding this - it looks like it was handled everywhere except in the Ruby 1.8 template for elasticsearch and logstash. Everything should be fixed now. I'll push a new release up to the forge soon.
