### ISSUE TITLE
versioncmp in params.pp

### ISSUE THREAD

**Issue by ralfbosz** [pcfens/puppet-filebeat#299]
In the latest version (4.11.1) there is a bug in params.pp for fresh-installs. When 'filebeat' is not installed yet, the fact 'filebeat-version' gives a 'false' which Puppet sees as Boolean which causes an error:

Error: Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Boolean (file: /etc/puppetlabs/code/modules/filebeat/manifests/params.pp, line: 172, column: 6) 

Version 4.11.0 does not have this error, the fault is in the params.pp:

https://github.com/pcfens/puppet-filebeat/blob/1511e005178ee2b3727419317f2871c037a2bd5d/manifests/params.pp#L172-L176

**Comment by sclaggett** [comment]
I just ran into this bug as well. My solution was to change the first line:

```
  if (!$facts['filebeat_version']) or (versioncmp($facts['filebeat_version'], '7.16') > 0) {
    $default_input_type = 'filestream'
  } else {
    $default_input_type = 'log'
  }
```

That works for me because I know the version of filebeat I'm using is greater than 7.16, but it certainly isn't the correct fix.

**Comment by sclaggett** [comment]
The same bug also exists in input.pp, line 57.

**Comment by ralfbosz** [comment]
> The same bug also exists in input.pp, line 57.

It is there but when it hits that a version of FileBeat Will be present.

**Comment by sclaggett** [comment]
> It is there but when it hits that a version of FileBeat Will be present.

Perhaps in theory, but somehow I encountered the bug there in practice.
