### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JGodin-C2C** [pcfens/puppet-filebeat#310]
Hello there !
Is it possible to have a new release ? the latest released version does not include the journald input module (Added here : #302 )and journalbeat is today deprecated. (https://www.elastic.co/guide/en/beats/journalbeat/current/journalbeat-overview.html)
Regards,

**Comment by pcfens** [comment]
I just tagged and pushed v4.12.0 to the Puppet forge a few minutes ago. Hopefully this takes care of issues for a lot of folks.
