### ISSUE TITLE
Need to fix some params as Integer in Redis output

### ISSUE THREAD

**Issue by Metrax** [pcfens/puppet-filebeat#38]
Please add these lines to the template:

> <%- if @filebeat_config['output']['redis']['db'] -%>
<%- @filebeat_config['output']['redis']['db'] = Integer(@filebeat_config['output']['redis']['db']) -%>
<%- end -%>
<%- if @filebeat_config['output']['redis']['db_topology'] -%>
<%- @filebeat_config['output']['redis']['db_topology'] = Integer(@filebeat_config['output']['redis']['db_topology']) -%>
<%- end -%>
<%- if @filebeat_config['output']['redis']['timeout'] -%>
<%- @filebeat_config['output']['redis']['timeout'] = Integer(@filebeat_config['output']['redis']['timeout']) -%>
<%- end -%>
<%- if @filebeat_config['output']['redis']['reconnect_interval'] -%>
<%- @filebeat_config['output']['redis']['reconnect_interval'] = Integer(@filebeat_config['output']['redis']['reconnect_interval']) -%>
<%- end -%>

Else filebeat cannot start:

> Aug 10 16:52:04 robert2 filebeat[44273]: Loading config file error: YAML config parsing failed on /etc/filebeat/filebeat.yml: yaml: unmarshal errors:
Aug 10 16:52:04 robert2 filebeat[44273]: line 15: cannot unmarshal !!str `0` into int
Aug 10 16:52:04 robert2 filebeat[44273]: line 16: cannot unmarshal !!str `1` into int
Aug 10 16:52:04 robert2 filebeat[44273]: line 17: cannot unmarshal !!str `5` into int
Aug 10 16:52:04 robert2 filebeat[44273]: line 18: cannot unmarshal !!str `1` into int. Exiting.

**Comment by pcfens** [comment]
Thanks for this. I've pushed a release with the fix to the forge as v0.7.4.
