### ISSUE TITLE
Instantiate Puppet resources (prospectors)

### ISSUE THREAD

**Issue by WILEC2** [pcfens/puppet-filebeat#39]
Hello,

I am using the prospectors parameters from the public class to instantiate the filebeat::prospector.
From what ive seen in the init.pp file you already have the 'create_resources' which means all resource properties/params can be passed in using puppet ENC.

` if !empty($prospectors_final) {
    create_resources('filebeat::prospector', $prospectors_final)
  }
`

I try to pass the following HASH in the prospector parameter...
`paths: ["/var/log/messages"] 
doc_type: syslog
`
and I get the following error.

no implicit conversion of Array into Hash at /etc/puppet/environments/production/modules/filebeat/manifests/init.pp:91

From what I understand the only required parameter for filebeat::prospector is paths which is an ARRAY. 

Any idea of what is causing this error?

I tested it without the prospector parameters and everything works fine. The filebeat repo is created and filebeat is installed. The custom filebeat.yml is created with the 'ouputs' and 'shippers' parameters that i've defined. When I add the prospector parameters I get the implicit conversion of Array error.

**Comment by pcfens** [comment]
The `prospectors` hash should end up looking something like
```puppet
{
  'system-logs'      => {
    paths    => [
      '/var/log/messages',
    ],
    doc_type => 'syslog',
  },
  'application-logs' => {
    paths    => [
      '/opt/myapplication/logs/*.log',
    ],
    doc_type => 'myapplication',
  },
}
```

What is normally the resource title is the key to a hash with the parameters attached. The full docs are on the [puppet functions page](https://docs.puppet.com/puppet/latest/reference/function.html#createresources).

I hope that helps.

**Comment by WILEC2** [comment]
Thank you, I got it working.

If you use Foreman as Puppet ENC and try to instantiate HASH variable you can add hashes in YAML format by selecting YAML from the type field (see [https://groups.google.com/forum/#!topic/foreman-users/p-XcMoxwbFk](url))

Foreman returned many different error while using 'HASH' type field, using YAML works just fine.
