### ISSUE TITLE
Tags variable missing in template

### ISSUE THREAD

**Issue by kariboe** [pcfens/puppet-filebeat#42]
Hello there,

There is an option to configure shipper tags in filebeat.yml.ruby18.erb but not in filebeat.yml.erb. Any specific reason why this is not possible?

Kind Regards,

Stefaan

**Comment by pcfens** [comment]
The filebeat.yml.erb template converts the entire hash that you pass it to YAML - the only parameters that are addressed directly are related to setting types more explicitly.

Have you tried passing it alone to see if it works?

**Comment by kariboe** [comment]
Thanks to make this more clear. First thing on my list to test tomorrow!

Op 14 sep. 2016, om 15:33 heeft Phil Fenstermacher <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The filebeat.yml.erb template converts the entire hash that you pass it to YAML - the only parameters that are addressed directly are related to setting types more explicitly.

Have you tried passing it alone to see if it works?

**Comment by pcfens** [comment]
Hi @kariboe - any chance you were able to test this?

**Comment by pcfens** [comment]
I'm going to go ahead and close this - if you're still having issues feel free to comment and I'll reopen it.
