### ISSUE TITLE
Add Filebeat v5 Support

### ISSUE THREAD

**Issue by pcfens** [pcfens/puppet-filebeat#44]

**Comment by pcfens** [comment]
This will capture #40 and #43

**Comment by joshuaspence** [comment]
It looks like Fielebeat v5 has been released.

**Comment by pcfens** [comment]
I still need to add a parameter so that the module can support both versions, but I want it to detect what it can (why I've added the filebeat_version fact).

The filebeat5 branch has what I've pushed so far. Using it with the right config template parameter set should work today if you want to try it out before it's all finished.

**Comment by dMopp** [comment]
Good work so far. I guess the most of us (at least me) can live with a "legacy" branch for older filebeat versions >5

Autodetection or a config value might be great but not required from my side

**Comment by pcfens** [comment]
It looks like the repository location for 5.x changed as well, so we'll need to manage that in addition to the template. In a way this makes things easier since there is less detection that we'll need to do.

I'm hoping that I get something more substantial pushed up later today

**Comment by pcfens** [comment]
I still need to update the docs, but some early testing would very much be appreciated before I roll a release out.

The quick and dirty version of the docs:
If you use this module on a system with filebeat 1.x installed, and you keep your current parameters nothing will change by default. Setting `major_version` to '5' will modify the configuration template and update package repositories, but won't update the package itself. To update the package use the `package_ensure` parameter (the current is 5.0.0).
