### ISSUE TITLE
Invalid options in output->logstash section of filebeat5.yml.erb

### ISSUE THREAD

**Issue by kobybr** [pcfens/puppet-filebeat#52]
The supported_protocols does not appear to be a valid option in the ssl configuration section.   I am not able to find a reference to this in elastic's documentation for logstash.   This section of code prevents module from working when ssl parameters are passed:

==> centos-7.2: Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template filebeat/filebeat5.yml.erb:
==> centos-7.2:   Filepath: /tmp/vagrant-puppet/modules-90cc3165c045baafa183f04f99186257/filebeat/templates/filebeat5.yml.erb
==> centos-7.2:   Line: 231

**Comment by pcfens** [comment]
Thanks. I've pushed this to the forge as v0.8.3
