### ISSUE TITLE
Incorrect indentation and/or mixed format in filebeat.yml causing service to not start

### ISSUE THREAD

**Issue by kobybr** [pcfens/puppet-filebeat#53]
Filebeat.yml extract:
#================================ Outputs =====================================

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts:
    - logstash.********************

    enabled: true
    certificate_authorities:
      - /var/lib/*********************
    certificate: "/var/lib/***************************"
    key: "/var/lib/*********************************"

Error message:

# service filebeat start
Starting filebeat: Exiting: error loading config file: yaml: line 59: did not find expected '-' indicator

expanding output.logstash to 
output:
  logstash:

fixes the problem as does removing the two leading spaces on the enabled, certifcate_authorities, certificate, and key.

**Comment by pcfens** [comment]
All fixed in v0.8.4
