### ISSUE TITLE
Package Update Does Not Notify Service

### ISSUE THREAD

**Issue by corey-hammerton** [pcfens/puppet-filebeat#56]
On a recent update to Package["filebeat"] I notice that messages were still being logged under the previous version. I upgraded from 5.0.0 to 5.0.1.

The logs state that Package["filebeat"] was updated and the next entry says "Finished catalog run"

Requesting that Class["filebeat::install", "filebeat::install::*"] notify Class["filebeat::service"] when the Package is updated.

**Comment by pcfens** [comment]
Thanks for pointing this out. I pushed what I think fixes this to the forge as v0.8.6.
