### ISSUE TITLE
Windows failing configtest

### ISSUE THREAD

**Issue by pellefrykman** [pcfens/puppet-filebeat#59]
I am using this module, version 0.8.6 and deploy FileBeat to a Windows Server 2012 R2 machine. The init.pp file is as follows:
class { 'filebeat':
  outputs => {
    'logstash'     => {
     'hosts' => [
       'logstash1a:47001'
     ],
    },
  },
}

The deployed FileBeat version is 1.3.1 (386) and the filebeat.yml file contains the following output section:
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts:
    - logstash1a:47001

When running filebeat.exe -configtest filebeat.yml I get the following result:
Error Initialising publisher: No outputs are defined. Please define one under the output section.

Changing the filebeat.yml file to
#----------------------------- Logstash output --------------------------------
output:
  logstash:
    hosts:
      - logstash1a:47001
makes the configtest pass.

I have puppet agent version 3.8.7 on the Windows Server and puppet master version 3.8.7 on Ubuntu 14.04.

**Comment by pcfens** [comment]
It looks like the module is pushing the filebeat 5 config template out to windows boxes. I suspect this will get fixed if you set the `major_version` parameter to 1.

Ultimately extending the filebeat_version fact should fix this too, but I don't have a windows dev environment ready to go to test everything.

**Comment by pellefrykman** [comment]
Yes, setting major_version to 1 worked fine. I was expecting the module to install Filebeat 5 if the default config format was version 5 compliant. I have a good Windows Environment, though I am a newbie when it comes to contributing on these kinds of projects. Let me know if I can assist in the development of this module in any way.
