### ISSUE TITLE
Template Checking for NilClass

### ISSUE THREAD

**Issue by corey-hammerton** [pcfens/puppet-filebeat#63]
In https://github.com/pcfens/puppet-filebeat/blob/master/templates/filebeat5.yml.erb#L34 it is currently checking if @filebeat_config['max_procs'] is :undef type, as seen below.

`<%- if @filebeat_config['max_procs'] != :undef -%>`

In all other if blocks they are checking for a nil value. For consistency's sake this :undef should be changed to nil.

This was uncovered after enabling the Future Parser on a Puppet 3.x environment.

**Comment by elconas** [comment]
Maybe this is fixed by https://github.com/pcfens/puppet-filebeat/pull/65

**Comment by corey-hammerton** [comment]
@elconas it is not fixed in #65

**Comment by pcfens** [comment]
What's the specific error message you're getting for this? Originally this was set to nil, but another issue was encountered. It was fixed in 8e5bcf3b.

**Comment by jarro2783** [comment]
I'm seeing this too. I don't know if it actually breaks anything. I suspect filebeat just uses the default value when this is empty. It would be nice not to have nil values set here though.
