### ISSUE TITLE
Apt repository won't install on ubuntu

### ISSUE THREAD

**Issue by serenapotts3** [pcfens/puppet-filebeat#66]
I am trying to install on Ubuntu 14.04 and get the following error:

Error: validate_re(): input needs to be a String, not a Hash at /etc/puppet/modules/apt/manifests/key.pp:62 on node XXX

I have the following in my puppet class:

    class { 'filebeat':
      outputs => {
        'elasticsearch' => {
         'hosts' => $hosts,
        },
        'index'  => 'packetbeat',
        'cas'    => [
           '/etc/pki/root/ca.pem',
        ],
      },
    }

I have version 2.3.0 of puppetlabs-apt and 0.8.7 of filebeats

It looks like filebeat::repo is failing to install the beats repo because the key is not valid.
Any ideas?

**Comment by pcfens** [comment]
What version of puppet are you using? I'm not able to replicate the issue.

**Comment by serenapotts3** [comment]
Puppet v3.8.1

**Comment by pcfens** [comment]
Are you using any other classes? I've tried tracing out the logic but I'm not sure what might be causing this.

Can you verify the version of puppetlabs/apt by checking the metadata.json file in the module?

**Comment by serenapotts3** [comment]
I do have a lot of other classes but if I set manage_repo to false then puppet continues on fine. I installed the repo manually and then everything worked, so definitely something to do with the repo class somehow.

confirmed apt is in metadata.json:

{
  "name": "puppetlabs-apt",
  "version": "2.3.0",
  "author": "Puppet Labs",
  "summary": "Provides an interface for managing Apt source, key, and definitions with Puppet",
  "license": "Apache-2.0",
  "source": "https://github.com/puppetlabs/puppetlabs-apt",
  "project_page": "https://github.com/puppetlabs/puppetlabs-apt",
  "issues_url": "https://tickets.puppetlabs.com/browse/MODULES",

**Comment by pcfens** [comment]
Did you ever figure out what was going on with this? Unfortunately I haven't been able to re-create the issue.

**Comment by serenapotts3** [comment]
No I haven't. I didn't get time to look into it further since then. I may need to get it working soon so I will let you know how I go.

**Comment by pcfens** [comment]
Any luck figuring this issue out? I haven't been able to reproduce it in any of our environments.

**Comment by serenapotts3** [comment]
In the end I decided not to use filebeat and am using fluentd, so I won't be spending time to work out the problem. I will close for now.
