### ISSUE TITLE
define hosts (filebeat5.yml.erb:)| prospectors error

### ISSUE THREAD

**Issue by smitjainsj** [pcfens/puppet-filebeat#67]
Error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template filebeat/filebeat5.yml.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/filebeat/templates/filebeat5.yml.erb
  Line: 197
  Detail: undefined method `each' for nil:NilClass
 at /etc/puppetlabs/code/environments/production/modules/filebeat/manifests/config.pp:29:20 on node elk-server.example.local

Hiera :

### Filebeat config
filebeat::outputs:
  'logstash':
    host: 'elk-server.example.local'
    port: 6379
    index: 'packetbeat'
    worker: 1

Any suggestions.

**Comment by pcfens** [comment]
The `host` parameter should be named `hosts` and be an array instead of a string.

Hopefully that fixes everything.

**Comment by smitjainsj** [comment]
Thanks Phil, I appreciate your efforts in maintaining this repo.
That solved but I am having some issues over setting prospectors, I hope if you can help in using them.

The prospectors are not getting created in the filebeat.yml 

### Filebeat config
filebeat::outputs:
  'logstash':
    hosts: [ "http://elk-server.example.local:5044" ]
    index: 'filebeat'
    worker: 1
filebeat::prospectors:
   'syslogs':
      paths: [ '/var/log/auth.log', '/var/log/syslog', ]
      doc_type: 'syslog-beat'
