### ISSUE TITLE
Modules support

### ISSUE THREAD

**Issue by apexlir** [pcfens/puppet-filebeat#73]
Nice feature coming to filebeat soon : 

https://github.com/elastic/beats/issues/3159

**Comment by pcfens** [comment]
That does look pretty nice to have. Once there's an RC or beta I'll take a look at adding support in (it's kind of hard to develop against when things aren't stable yet).

**Comment by pcfens** [comment]
I'm always open to PRs too if someone else has time and beats me to this. :smiley:

**Comment by pcfens** [comment]
Can you take a look to see if you can use modules in version 2? If not, I think it's a simple modification to add them in that I can do.

Thanks!

**Comment by jhoblitt** [comment]
Support for modules would be fantastic.

**Comment by devinmatte** [comment]
Is there module support yet or is there a planned feature for it?
I have just been running `filebeat modules enable system` on every system so far, but I was wondering if there was better support in this module?

**Comment by pcfens** [comment]
I believe this was fixed in #204, so I'm going to close it here. Please feel free to comment if I'm not understanding correctly.
