### ISSUE TITLE
Default settings do not work on Windows

### ISSUE THREAD

**Issue by lahma** [pcfens/puppet-filebeat#75]
There's space in default path C:\Program Files\Filebeat so this will fail in prospectors.pp:

     validate_cmd => "${filebeat_path} -N -configtest -c %",

Windows doesn't understand spaces in path. It should probably be:

     validate_cmd => "\"${filebeat_path}\" -N -configtest -c \"%\"",

**Comment by pcfens** [comment]
I've pushed your suggested fix to the [validate_windows_fix](https://github.com/pcfens/puppet-filebeat/tree/validate_windows_fix) branch. If you're able to test the fix I'd very much appreciate it- I don't have any Windows machines readily available for testing.

**Comment by lahma** [comment]
Thanks for your prompt reply, I did manually the changes (found out that the config.pp required changes too). With manually making these two changes I was able to run the main setup I was trying. Service installed successfully.

**Comment by pcfens** [comment]
Thanks for the quick check - I merged the fix into master and will push the updated version to the forge as soon as all the tests pass.

Thanks again

**Comment by lahma** [comment]
My pleasure, thanks for the quick resolution!
