### ISSUE TITLE
"Could not enable filebeat" error, though working.

### ISSUE THREAD

**Issue by williamayerst** [pcfens/puppet-filebeat#86]
Running Debian 16.04 in Azure, using Puppet Agent (and Server) 4.8.1 and latest Filebeat module from the Forge.

Everything works, but each time the agent runs, there's an error:

```Debug: /Stage[main]/Profiles::Filebeat/Notify[filebeat]: The container Class[Profiles::Filebeat] will propagate my refresh event
Debug: Class[Profiles::Filebeat]: The container Stage[main] will propagate my refresh event
Debug: Prefetching apt_key resources for apt_key
Debug: Executing: '/usr/bin/apt-key adv --list-keys --with-colons --fingerprint --fixed-list-mode'
Debug: Executing: '/bin/systemctl is-active filebeat'
Debug: Executing: '/bin/systemctl is-enabled filebeat'
Debug: Executing: '/bin/systemctl unmask filebeat'
Debug: Executing: '/bin/systemctl enable filebeat'
Error: Could not enable filebeat:
Debug: Executing: '/bin/systemctl is-enabled filebeat'
Error: /Stage[main]/Filebeat::Service/Service[filebeat]/enable: change from false to true failed: Could not enable filebeat:
Debug: Class[Filebeat::Service]: Resource is being skipped, unscheduling all events
Notice: /Stage[main]/Filebeat/Anchor[filebeat::end]: Dependency Service[filebeat] has failures: true
Warning: /Stage[main]/Filebeat/Anchor[filebeat::end]: Skipping because of failed dependencies
```

I would be grateful for any assistance.

Cheers,

**Comment by pcfens** [comment]
Could you try running filebeat manually to see what the output looks like (the command that systemd is using for me is `/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat`)? Make sure that you're running it as a user with rights to write in those directories.

**Comment by williamayerst** [comment]
Well like I said, the actual module is working perfectly with multiple prospectors - it's just when the puppet agent runs that I receive this error.

Running your exact command doesn't return anything (just sits at a blank prompt)

**Comment by pcfens** [comment]
Do you get any useful output when you run the problem command (`sudo systemctl enable filebeat`) manually?

**Comment by williamayerst** [comment]
Ah, I get an error from another startup script which was being run with the systemctl enable process (it happens to be the UpTime monitoring agent - a known issue, but I  didn't realise this would flag it - I think this is resolved?)

```
root@svr0:~# sudo systemctl enable filebeat
Synchronizing state of filebeat.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable filebeat
insserv: warning: script 'S99uptm_daemon' missing LSB tags and overrides
insserv: There is a loop at service plymouth if started
insserv: Starting upt_daemon.sh depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting upt_daemon.sh depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting upt_daemon.sh depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting upt_daemon.sh depends on plymouth and therefore on system facility `$all' which can not be true!

```

**Comment by williamayerst** [comment]
Yes, I can confirm fixing the runlevels on the unrelated init script caused this job to run successfully - I guess something for one to bear in mind is the dependency that other init scripts are OK when running a systemctl enable command as part of this module?

Thank you very much, couldn't have done it without your help.
