### ISSUE TITLE
Support for document_type

### ISSUE THREAD

**Issue by shaunrampersad** [pcfens/puppet-filebeat#9]
Hi @pcfens 

Can you include support for the document_type parameter? This will help tremendously.

Thanks
Shaun

**Comment by mkrakowitzer** [comment]
It is supported using the ':log_type' parameter.

**Comment by shaunrampersad** [comment]
thanks @mkrakowitzer

**Comment by pcfens** [comment]
It's a bug that the parameter name doesn't match the documentation (it may have been changed during an earlier rc/beta release).

I'm going to work on supporting both (so I don't break modules that are already being used), and look at deprecating `log_type` sometime before we get to 1.0.

**Comment by pcfens** [comment]
Looking through everything, it looks like its always been called document_type - I'm not sure why I didn't call it that originally. I'll hopefully have a new version with the updated field name out later today.

Thanks @shaunrampersad for pointing this out, and to @mkrakowitzer for jumping in so quickly with an answer.

**Comment by pcfens** [comment]
After pushing a bugfix and updating my puppet master I remember why I didn't use `document_type` before - it causes a pson error when using a puppet master.

Is there a term that makes more sense than `input_type`?

**Comment by shaunrampersad** [comment]
Hi @pcfens 

Just a suggestion, but doc_type might be a better term as it is closer to the original name.

**Comment by pcfens** [comment]
Thanks - this does make a lot more sense. I'll hopefully tag and push v0.5 later today.
