### ISSUE TITLE
Module doesn't work when strict vars are on

### ISSUE THREAD

**Issue by electrical** [pcfens/puppet-filebeat#92]
Hiya. When strict variables are on the module doesn't work.
The first place that gets hit is https://github.com/pcfens/puppet-filebeat/blob/master/manifests/init.pp#L93
$::filebeat_version fact doesn't exist and with strict variables it blows up.
`Evaluation Error: Unknown variable: '::filebeat_version'.`

You might want to run some acceptance tests with strict vars enabled and fix some things ;-)

**Comment by pcfens** [comment]
Thanks for finding this - I thought I was testing using strict variables so I'll dive in a little bit deeper.

Aside from better testing, this should be fixed in ede4c4a. I'll push an updated release to the forge soon.

**Comment by electrical** [comment]
Thanks or fixing it so quick! Will report if i find anything else.
