### ISSUE TITLE
Could not find dependent Service[filebeat] on v0.10.4

### ISSUE THREAD

**Issue by erikmathis** [pcfens/puppet-filebeat#93]
Error: Failed to apply catalog: Could not find dependent Service[filebeat] for File[filebeat-nginx] at /etc/puppet/modules/filebeat/manifests/prospector.pp:60

Puppet 3.8 on centos7

I ended up adding "include filebeat::service" near the top to get past this error.

**Comment by pcfens** [comment]
Are you defining prospectors when you declare the filebeat class (hiera or in the manifest) or in separate `filebeat::prospector` declarations?

**Comment by erikmathis** [comment]
I have a simple abstraction class to get filebeat installed with a base config.
`	class { 'filebeat':
		major_version => '5',
		manage_repo => false, #uses internal rpm repo
		tags	=> [$::environment, $tinyenv ],
		outputs => {
			'logstash' => {
				'hosts' => [ "$logstash_host:$logstash_port" ],
				'loadbalance' => false,
			}
		}
	}

	$bslog="/var/log/bs.log"
	file {$bslog: ensure => file, require => Class[filebeat::install]  } #empty file to get the ball rolling
	filebeat::prospector { 'BS-log':
		paths    => [ $bslog ],
		doc_type => 'syslog-beat',
		require	=> [ File[$bslog] ]
	}`

Then I have focused bits
 `	filebeat::prospector { 'nginx':
		paths    => [ '/var/log/nginx/*.log' ],
		doc_type => 'nginxcore',
		fields_under_root => true
	}
`

**Comment by csoleimani** [comment]
Are both of those resources in the same manifest? You'll need to require the first one if they're in separate files

**Comment by pcfens** [comment]
@erikmathis Were you able to figure this one out? If there's a bug I'd like to fix it.

Thanks!

**Comment by pcfens** [comment]
I'm going to go ahead and close this - if you're still having issues feel free to comment and I'll re-open it.
