### ISSUE TITLE
Implement index conditional match in output elasticsearch

### ISSUE THREAD

**Issue by cristianocasella** [pcfens/puppet-filebeat#96]
Like described here:

https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_indices

Filebeat support the ability to split in different index depending, as a sample, to a field match (field 'message' in the example).

In your module this condition is not supported.

From templates/filebeat5.yml.erb (@100-102):
```
  <%- if @filebeat_config['output']['elasticsearch']['index'] != nil -%>
  index: "<%= @filebeat_config['output']['elasticsearch']['index'] %>"
  <%- end -%>
```
the support for an array 'indices' containing for each index a condition could be implemented.

**Comment by pcfens** [comment]
Fixed in #97 

Thanks again @cristianocasella
